"""empty message

Revision ID: c39bd25781ae
Revises: 661c079fe203
Create Date: 2018-12-21 13:48:10.501900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39bd25781ae'
down_revision = '661c079fe203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'published')
    # ### end Alembic commands ###
